(function(){
'use strict';
if(!/^(127\.0\.0\.1|localhost|www\.tsakurai\.com)$/.test(location.hostname)||new URLSearchParams(location.search).get('ts_debug')!=='1'||window.tsTransportDebug)return;
window.tsTransportDebug=true;
var rows=[],next=0;try{rows=JSON.parse(sessionStorage.getItem('ts.qa.sanitized-transport')||'[]');next=rows.length?rows[rows.length-1].id:0;}catch(_){}
function display(){try{sessionStorage.setItem('ts.qa.sanitized-transport',JSON.stringify(rows));}catch(_){}var p=document.getElementById('qa-transport');if(!p){if(!document.body)return;p=document.createElement('pre');p.id='qa-transport';p.setAttribute('aria-label','Sanitized Adobe transport log');p.style.cssText='white-space:pre-wrap;background:#fff;color:#111;border:3px solid #167;padding:12px;font:12px monospace;position:fixed;bottom:0;right:0;width:40vw;max-height:20vh;overflow:auto;z-index:999999;pointer-events:none';document.body.appendChild(p);}p.textContent=JSON.stringify(rows,null,2);}
function begin(raw,kind,body){try{var u=new URL(raw,location.href);if(!/\.(adobedc\.net|omtrdc\.net)$/.test(u.hostname)&&!/^s?metrics\.tsakurai\.com$/.test(u.hostname))return null;var q=new URLSearchParams(u.search);if(typeof body==='string'&&body[0]!=='{')new URLSearchParams(body).forEach(function(v,k){q.set(k,v);});var fields={};['pageName','events','products','pe','pev2','v151','v152','v153','v154','v155','v156','v157','v158','v159','v160','v161','v162'].forEach(function(k){if(q.has(k))fields[k]=q.get(k);});if(q.has('purchaseID'))fields.purchaseID='present-redacted';if(q.has('g')){var g=new URL(q.get('g'));fields.pageURL=g.origin+g.pathname;fields.pageURLHasQuery=!!g.search;}if(typeof body==='string'&&body[0]==='{'){var payload=JSON.parse(body),event=payload.events&&payload.events[0],aa=event&&event.data&&event.data.__adobe&&event.data.__adobe.analytics;if(aa){['pageName','events','linkType','linkName','eVar151','eVar152','eVar153','eVar154','eVar157','eVar158','eVar161'].forEach(function(k){if(aa[k]!==undefined)fields[k]=aa[k];});if(aa.pageURL){var page=new URL(aa.pageURL);fields.pageURL=page.origin+page.pathname;fields.pageURLHasQuery=!!page.search;}var web=event.xdm&&event.xdm.web;if(web&&web.webPageDetails&&web.webPageDetails.URL){var xp=new URL(web.webPageDetails.URL);fields.xdmURLHasQuery=!!xp.search;}}}var row={id:++next,kind:kind,host:u.hostname,path:u.pathname.replace(/\/s\d+$/,'/request'),status:'started',fields:fields};rows.push(row);if(rows.length>100)rows.shift();display();return row;}catch(_){return null;}}
function end(row,status){if(row){row.status=status;display();}}
var desc=Object.getOwnPropertyDescriptor(HTMLImageElement.prototype,'src');Object.defineProperty(HTMLImageElement.prototype,'src',{configurable:desc.configurable,enumerable:desc.enumerable,get:desc.get,set:function(url){var row=begin(url,'image');if(row){this.addEventListener('load',function(){end(row,'image-load-success');},{once:true});this.addEventListener('error',function(){end(row,'image-load-error');},{once:true});}return desc.set.call(this,url);}});
var open=XMLHttpRequest.prototype.open,send=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.open=function(method,url){this.__qaURL=url;return open.apply(this,arguments);};XMLHttpRequest.prototype.send=function(body){var row=begin(this.__qaURL,'xhr',body),self=this;if(row)this.addEventListener('loadend',function(){end(row,'HTTP '+self.status);},{once:true});return send.apply(this,arguments);};
var beacon=navigator.sendBeacon;navigator.sendBeacon=function(url,data){var row=begin(url,'beacon',typeof data==='string'?data:undefined);var result=beacon.apply(this,arguments);end(row,result?'beacon-queued':'beacon-rejected');if(row&&data instanceof Blob)data.text().then(function(body){var details=begin(url,'beacon-body',body);if(details)end(details,result?'beacon-queued':'beacon-rejected');});return result;};
var fetch0=window.fetch;window.fetch=function(input,init){var row=begin(typeof input==='string'?input:input.url,'fetch',init&&init.body);return fetch0.apply(this,arguments).then(function(r){end(row,'HTTP '+r.status);if(row&&row.path.indexOf('/ee/')===0&&r.clone)r.clone().json().then(function(body){row.edgeErrorCount=Array.isArray(body.errors)?body.errors.length:0;row.edgeWarningCount=Array.isArray(body.warnings)?body.warnings.length:0;row.edgeHandleTypes=(body.handle||[]).map(function(h){return /^[a-zA-Z:_-]{1,60}$/.test(h.type||'')?h.type:'redacted';});display();}).catch(function(){});return r;},function(e){end(row,'fetch-error');throw e;});};
document.addEventListener('DOMContentLoaded',display);
})();
